# Generated by Django 2.2 on 2019-06-11 11:52

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingleTableDbFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('content', models.BinaryField(blank=True)),
                ('created_ts', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('updated_ts', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'storage_file',
            },
        ),
    ]
